# 개발 환경 설정
spring:
  # 데이터베이스 설정 (개발용 PostgreSQL)
  datasource:
    url: jdbc:postgresql://fehu.kr:5432/cursor_erp_system
    username: cursor_erp_system
    password: cursor_erp_system
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
  
  # JPA 설정 (개발용)
  jpa:
    hibernate:
      ddl-auto: none  # DDL 자동 생성 비활성화
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # SQL 초기화 설정 (data.sql 사용)
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql,classpath:import.sql
      schema-locations: classpath:schema.sql
      continue-on-error: true

# 로깅 설정 (개발용)
logging:
  level:
    com.erp: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE