# 운영 환경 설정
spring:
  # 데이터베이스 설정 (운영용 PostgreSQL - 개발 DB와 동일)
  datasource:
    url: jdbc:postgresql://fehu.kr:5432/cursor_erp_system
    username: cursor_erp_system
    password: cursor_erp_system
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  
  # JPA 설정 (운영용)
  jpa:
    hibernate:
      ddl-auto: none  # DDL 자동 생성 비활성화
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true

# 로깅 설정 (운영용)
logging:
  level:
    com.erp: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: WARN
  file:
    name: /var/log/erp-system/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

